### ISSUE TITLE
Hijri DateTimeRangePicker

### ISSUE THREAD

**Issue by aziz1117** [mominsamir/smDateTimeRangePicker#1]
I search a lot for Hijri calendar as picker in internet, i did not found. Could you please adjust this code to be able to Pick Hijri calendar.

**Comment by mominsamir** [comment]
I am working on it should be done by 20th this month, may be I will create a new repo

**Comment by aziz1117** [comment]
Thank you a lot, i am excited to see it 👍

**Comment by mominsamir** [comment]
found some issue with hizri date picker i have created, once issue resolved i will create repo

**Comment by mominsamir** [comment]
hay created new repo with name smHijriDatePicker please check it
