### ISSUE TITLE
The value of onRangeSelect callback should return moment objects

### ISSUE THREAD

**Issue by oscar09** [mominsamir/smDateTimeRangePicker#100]
onRangeSelect callback returns the date as strings. It would be useful to return them as moment objects as well. See #93.

**Comment by pablorsk** [comment]
Great! Then the proposal is, in date-range-picker case, this:

```javasctipt
ngModel = {
  startDateMoment: moment_object,
  endDateMoment: moment_object
}
```

Another proposal is use this:
```javasctipt
ngModel = {
  startDate: moment_object,
  endDate: moment_object
}
```

Also, callback parameter is not very important now, becouse on callback is possible access to ngModel.

I'm working on a proposal, is not very difficult.

**Comment by oscar09** [comment]
Moment object are returned on the properties "startDateAsMoment" and "endDateAsMoment". Documentation was updated as well.

**Comment by pablorsk** [comment]
@oscar09  what is the npm version?

**Comment by oscar09** [comment]
on my machine? 3.5.2

**Comment by pablorsk** [comment]
sorry, I ask about publish this library. 

you can do `npm publish` or can do only @mominsamir?

**Comment by oscar09** [comment]
The change is already merged. Pull request #103 and commit #618b665dd0c66fa711a1c54aa0ff50d58fab68ac

**Comment by oscar09** [comment]
I did not run npm publish nor created a different tag because I am not sure if tags are created when several features/bugs have been fixed and tested.

**Comment by mominsamir** [comment]
you can create new tag if this is bug fix to x.x.7 from earlier version x.x.6 for some major enhancement create tag to x.1.x from current  x.0.x. last for breaking changes update entire version to 3.x.x from 2.x.x

push new tag as per ur changes and i will publish on npm

**Comment by oscar09** [comment]
Tag v2.0.7 was created.
I just noticed you also have a "develop" branch. Shall we keep adding changes on the master branch or the develop branch?

**Comment by mominsamir** [comment]
This version can not be publish as you missed to update package.json file. only if version is matching to package json npm publish can be run.

You may create your own branches for development and later merge it with master branch (this way is better, less conflicts ), or you can work on master branch it self (more conflicts).

{
  "name": "smdatetimerangepicker",
  "version": "2.0.7",
  "description": "angular material Date Time Range Picker",

**Comment by oscar09** [comment]
I missed that, I will update the file.

**Comment by mominsamir** [comment]
it can be publish with old version tag please update with tag 2.0.8

**Comment by oscar09** [comment]
done

**Comment by mominsamir** [comment]
published with npm
