### ISSUE TITLE
disable with button click

### ISSUE THREAD

**Issue by lashisu** [mominsamir/smDateTimeRangePicker#114]
How can we disable Date Picker from a button click. It is not working through ng-disabled/disabled attribute. Please see. Preview is here on plunker:-

http://plnkr.co/edit/x15vDdF9WFG3Nq5eJiP4?p=preview

**Comment by lashisu** [comment]
@mominsamir any luck for me?

**Comment by oscar09** [comment]
As a workaround, you could put the date picker element between a fieldset .. something like this:
```

<fieldset ng-disabled="disable">
 <sm-date-picker> ...
</fieldset>
```

**Comment by lashisu** [comment]
Thanks a lot
