### ISSUE TITLE
start date for date range picker is set as date - 1 day

### ISSUE THREAD

**Issue by oscar09** [mominsamir/smDateTimeRangePicker#122]
When the start date is set on the date range picker the value is set as date - 1 day. This means, that if I select January 22, the value is set as January 21.

**Comment by wesleifreitas** [comment]
@oscar09
Are you already fixing this problem?

**Comment by oscar09** [comment]
Yes

**Comment by oscar09** [comment]
If you already spot the problem, feel free to fix this bug. I have been kind of busy lately and haven't had a chance to continue with the debug process. Otherwise, I will try to fix it tonight.

**Comment by oscar09** [comment]
this has been fixed.

**Comment by oleg-demkovych** [comment]
Have this bug with latest version
