### ISSUE TITLE
Clear button is not working in angular 1.6.1

### ISSUE THREAD

**Issue by glukamin** [mominsamir/smDateTimeRangePicker#125]
When I set allow-clear="true" for sm-range-picker-input clear button is just not being shown. In developer tool of chrome line for this button is commented. I've used your plunker code where version of angular was 1.3.15 and changed it to 1.6.1 and clear button is not being shown.

**Comment by oscar09** [comment]
I believe this is related to the fact that angular material is not fully  compatible with angular >1.6. see:
https://github.com/angular/material/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%201.6

**Comment by mominsamir** [comment]
can i close this issue if its fixed.

**Comment by glukamin** [comment]
Yes, sure. Thanks
