### ISSUE TITLE
setCustomHeader

### ISSUE THREAD

**Issue by salva-b** [mominsamir/smDateTimeRangePicker#13]
Hi Samir, thx for this new great option.
I've seen if mode is not set in date-time-picker allways returns default option.

**Comment by mominsamir** [comment]
Yes you are right, setCustomHeader depends on mode to display selected time, if no mode is selected it displays default format. so you can use three of this options to set mode 'date,date-time, time'

**Comment by salva-b** [comment]
Great! Thx
