### ISSUE TITLE
Unable to set both min and max date

### ISSUE THREAD

**Issue by preraksola** [mominsamir/smDateTimeRangePicker#137]
When I both `min-date` and `max-date` it only allows me to select today's date. 
Here's the plunker with the issue: http://plnkr.co/edit/Jjs1rPiC5F6td3FNXld0?p=preview

Is there anything that I am missing?

**Comment by oscar09** [comment]
I believe the code is wrong. The text says that the min date is set as "03-20-2016" and max date as "10-20-2016" but if you print the values for minDate and maxDate you will get:
MinDate: 27-10-2016
MaxDate: 27-03-2017

which are the dates that are being used as max & min by the component.
