### ISSUE TITLE
Return previous day

### ISSUE THREAD

**Issue by oleg-demkovych** [mominsamir/smDateTimeRangePicker#151]
When i select start day (on date range picker), the selected value decresed by 1, i.e.:
04/06/2017->03/06/2017

**Comment by oscar09** [comment]
Please test with latest code. It should be fixed now.

**Comment by oleg-demkovych** [comment]
I used v.2.0.10, but issue still happened

**Comment by oleg-demkovych** [comment]
`<sm-range-picker-input
              fname="Date"
              label="Date"
              ng-model="transactionsCtrl.defaultData"
              format="MM/DD/YYYY"
              flex="100"
              min-date="01/01/2017"
              max-date="12/30/2199"
              divider="-"
              week-start-day="Monday"
              on-range-select="transactionsCtrl.applyDateFilter(range)"
              custom-to-home="'true'">`

**Comment by oleg-demkovych** [comment]
Here is video with issue
http://take.ms/7ms04

**Comment by oscar09** [comment]
I believe this issue is fixed in the master version. Not sure why the demo page is not working any more. I will bring it up again and you can test your scenario there.

**Comment by oleg-demkovych** [comment]
hm. I found how to fix this issue:
**1604:** `date = moment(date);`

```
RangePickerCtrl.prototype.startDateSelected = function(date){
    date = moment(date);
    this.startDate = date;
    this.minStartToDate = date;
    this.scope.$emit('range-picker:startDateSelected');
    this.setNextView();

    if (this.endDate && this.endDate.diff(this.startDay, 'ms') < 0) {
        this.endDate = date;
    }
}
```

**Comment by oscar09** [comment]
I just pushed tag 2.0.11 please try with that version.

**Comment by oleg-demkovych** [comment]
Thanks. Working well
