### ISSUE TITLE
date range picker end date validation problem.

### ISSUE THREAD

**Issue by Devarajsingh89** [mominsamir/smDateTimeRangePicker#178]
Hi,

smDateTimeRangePicker if i am selecting start date as for example "15-Mar-2018 01:01 AM" and if want to select end date as "15-Mar-2018 6:30 PM" its not allowing, the 15 in end date is disabled.

**Comment by rahimnagori** [comment]
Hello @oscar09 ,
How are you?
I need to apply dynamic validations on end date.
Could you please help me with it?

**Comment by oscar09** [comment]
what do you mean by dynamic validations? how are you planning to use it?

**Comment by rahimnagori** [comment]
There is an option 
**max-date=moment()**
which only allow selecting max date as today's date for the case of Range Picker.
I need to apply max date validation for all the cases :
Today
Week
Month
Range
How to achieve this?

**Comment by rahimnagori** [comment]
And one more thing can I display only one option in date range picker?
![image](https://user-images.githubusercontent.com/42448371/55948768-d9199080-5c6e-11e9-8fc1-4968464767dc.png)
Marked in blue.

**Comment by rahimnagori** [comment]
I got something : 
![image](https://user-images.githubusercontent.com/42448371/55952469-534e1300-5c77-11e9-8adc-a5f0deb39627.png)

**Comment by oscar09** [comment]
The issue has been fixed. You should be able to use the custom list in the followign way:

    vm.customList = [
        {
            position: 0,
            label: 'Holy Week',
            startDate: moment('2019-04-14'),
            endDate: moment('2019-04-20')
        }

    ];

html attr:
`custom-list="vm.customList"`

and you will get something like this:

![image](https://user-images.githubusercontent.com/4185816/55970319-f0438880-5c44-11e9-8fdb-acd0e449d5a8.png)

**Comment by oscar09** [comment]
max-date property grays out the dates after the set max date. If you need to run specific validations (if the selected day is a weekend for example) you could do it in the oRangeSelect method. The returned objects are moment objects and it already has methods to check those kind of constraints.

max-date should take the date as moment or as max-date="11-10-2016" (assuming that you set the format as DD-MM-YYYY)

**Comment by rahimnagori** [comment]
I'm trying to apply max date validation as :
Controller : 
`$scope.maxDate = 'MM/DD/YYYY';`
View File : 
`max-date="moment(maxDate)"`
Now it is not working. Any idea?

**Comment by oscar09** [comment]
Moment js takes a date string and converts it to moment object. It should be able to parse a date that comes with the format mm/dd/yyyy. Which date are you passing ?
