### ISSUE TITLE
Kindly create a new release for the resolved bug

### ISSUE THREAD

**Issue by AvinashNip** [mominsamir/smDateTimeRangePicker#185]
Hello,
Right now I am facing an issue, which is described in bug #147. Good thing is that it has been resolved by your team. Now kindly create a new release so that I can find the latest changes using bower update command. 

Currently latest release is V2.0.11, which does not contain solution of bug #147 
![image](https://user-images.githubusercontent.com/45005764/48417716-6ec0fa80-e779-11e8-9d89-6e24d68b07b9.png)

Thanks,
Avi

**Comment by oscar09** [comment]
Tag has been created.
