### ISSUE TITLE
Issue with date picker and chrome ver. 73

### ISSUE THREAD

**Issue by ghost** [mominsamir/smDateTimeRangePicker#186]
Hello, 
It seems that the new update of chrome has broke the datetime picker. The problem is that as soon as you click on the input it opens the picker and closes it immediately. You can reproduce it in the demo [plunker](http://plnkr.co/edit/2ePb5nf8vH71iH5byP7q?p=preview) in the "Demo For Date Range Picker".
I solve it temporarily changing the ng-focus to ng-click, but with this solution the tab focus is not working

**Comment by oscar09** [comment]
This is the same problem described in #187. I will work on that one and close this issue.
