### ISSUE TITLE
SM Date Time Range Picker not opening properly.

### ISSUE THREAD

**Issue by rahimnagori** [mominsamir/smDateTimeRangePicker#187]
When I click on the input field where range picker is applied. It doesn't opens just open for a short time and than close. Seems like clicking on the input looses focus to the range picker.
@oscar09 , could you please look into this?

**Comment by oscar09** [comment]
I found this issue last week and applied a temp fix in my fork. The problem is related to the latest update in Chrome, but I don't know what exactly the issue is.

I will take a deeper look to find a proper fix.

**Comment by yehuda** [comment]
Could you give us your temp fix please?

**Comment by rahimnagori** [comment]
Hello @oscar09 ,
Thank you for noticing this.
 Could you provide your temporary fix?

**Comment by oscar09** [comment]
Hi guys, sorry I have been busy lately. I will work on the bug this week.
Meanwhile, you can find the temp fix in branch "bug187.temp_fix". Let me know if you find any issues.

**Comment by oscar09** [comment]
I have posted the final fix in master and tag v 2.0.13. Let me know if you find any issues.

**Comment by rahimnagori** [comment]
> I have posted the final fix in master and tag v 2.0.13. Let me know if you find any issues.

I'll check and let you posted about it. Thank you.

**Comment by rahimnagori** [comment]
Fixed. Thanks @oscar09
