### ISSUE TITLE
week-start-date seems not working

### ISSUE THREAD

**Issue by nebu4** [mominsamir/smDateTimeRangePicker#2]
Hello,

Nice work here! I really like it.
I tried several days as week-start-day attribute but it doesn't seem to work, even in your [plunker](http://plnkr.co/edit/2ePb5nf8vH71iH5byP7q?p=preview).

I use it with Angular v1.3, angular-material v0.11.4 and moment 2.10.6.

Thx

**Comment by mominsamir** [comment]
I will check and fix it if it is a bug. Thanks

**Comment by aziz1117** [comment]
Hi,
How i can choose Hijri calendar?

Thanks
