### ISSUE TITLE
Interface blocked on open two times Dialog window

### ISSUE THREAD

**Issue by salva-b** [mominsamir/smDateTimeRangePicker#20]
Hi Samir,
seems like something is blocking interface after opening datepicker in a dialog window more than once.
You can test it in your plunker example.

**Comment by mominsamir** [comment]
This is known issue, it is caused by angular material dialoge service md-scroll-mask.

its bug and work around for that is 
`vm.showCalander = function(ev){
          options.targetEvent = ev;
          smDateTimePicker(vm.currentDate,options)
          .then(function(selectedDate) {
            vm.currentDate = selectedDate;
            var ele = document.getElementsByClassName("md-scroll-mask");
            if(ele.length!==0){ 
                angular.element(ele).remove();
            }            
          });          
        }
`

you cann removed it once ur date is selected
