### ISSUE TITLE
auto change date format to milliseconds format

### ISSUE THREAD

**Issue by osamabari** [mominsamir/smDateTimeRangePicker#23]
when i submit the form then date automatically convert into milliseconds.

**Comment by mominsamir** [comment]
Can u provide me ur code, on how u use it.

**Comment by osamabari** [comment]
hi  m using this code:
`<sm-range-picker-input  initial-date="05-24-2016"  fname="date" lable="Date range" form="discountfrm" value="d.var_date"   format="MM-DD-YYYY" divider="To" mode="date"  week-start-day="Sunday"></sm-range-picker-input >`  

date  automatically change to milliseconds(1464174232813 To 1464201000000)  on form submitting.

**Comment by osamabari** [comment]
<sm-range-picker-input  initial-date="05-24-2016"  fname="date" lable="Date range" form="discountfrm" value="d.var_date"   format="MM-DD-YYYY" divider="To" mode="date"  week-start-day="Sunday">
	        </sm-range-picker-input >

**Comment by mominsamir** [comment]
How u are handling this in ur controller. It seems this happened due to moment object it retuned is manipulated in ur controller.

**Comment by osamabari** [comment]
m just add in my controller and using it

`.controller('DiscountController', function ($http, $scope,$moment) 
`
please suggest me if i have t  add something else;

**Comment by mominsamir** [comment]
code where u submit ur form data using http

**Comment by osamabari** [comment]
//FUNCTION CALLED WHEN USER SUBMIT FORM
` ```
 vm.createDiscount = function () {
    vm.processing = true;
                    vm.error = '';
                    vm.success = '';
                    vm.user = '';
                    vm.multi_vars = {};
                    if ($scope.cd.bydayordate == "day") {
                        vm.multi_vars = $scope.rows;
                    } else {
                // $scope.rowsDate  IS ARRAY TO STORE MY ROWAS AS ARRAY LIKE "{"var_date":"05-26-2016 To 05-26-2016","discount_date":"75","StartTime_d":"08:00:00","EndTime_d":"16:59:59"}"

```
                    vm.multi_vars = $scope.rowsDate;


                }
         //SERVICE WHICH CALL HTTP REQUEST
                Discount.createDiscount($scope.cd, vm.multi_vars);
            }
```

)

``````

//SERVICE DEFINATION
    .```
factory('Discount', function ($http, $q, Auth, $moment, $location) {
     var discountFactory = {};
  discountFactory.createDiscount = function (r_data, variable) {
                var m_id = false;
                console.log(r_data,variable);
                Auth.getUser()
                        .then(function (data) {

                            m_id = data.data.id;
                     //CALLING HTTP REQUEST TO API
                            return $http.post('/api_merchent/create_discount', {
                                data: r_data,
                                variable: variable,
                                m_id: m_id
                            }).success(function (data) {
                                data = JSON.parse(data);

                                // return data;
                                $location.path('/discount');
                                console.log(data);
                            }).error(function (err) {
                                console.log(err);
                            })
                        });
  return discountFactory;

        })
``````

**Comment by mominsamir** [comment]
ur code seems good, only thing that bothers me is $moment service.

range picker returns string and not moment object. so somehow somewhere ur controller or service converting string returned by range picker into moment object and converting to unix date object using $moment service.

if you are not $moment service is not required then you can remove it.

**Comment by osamabari** [comment]
no effect after removing $moment service.
please help me out.

**Comment by mominsamir** [comment]
this is bug in my directive, i have to check, one its fixed i will close this issue.
