### ISSUE TITLE
Show selected date in datepicker service

### ISSUE THREAD

**Issue by salva-b** [mominsamir/smDateTimeRangePicker#24]
Hi Samir,
how can I show selected date using datepicker as a service?
Thx

**Comment by mominsamir** [comment]
Where u want to show it ???

**Comment by salva-b** [comment]
In datepicker's left panel. Always opens with the current date

**Comment by mominsamir** [comment]
check now if ur issue is fixed

**Comment by salva-b** [comment]
Fixed! Thx!!

**Comment by eh-am** [comment]
How did you do @salva-b? I didn't get it.
