### ISSUE TITLE
change event on select date / datetimerange

### ISSUE THREAD

**Issue by salva-b** [mominsamir/smDateTimeRangePicker#25]
Hi Samir,
can I bind to any event when date time range is selected (window closed) ?

**Comment by mominsamir** [comment]
Yes you can bind it, however can you tell me what exactly you wish to do with it. So if requires I can add that feature if it does not exists

**Comment by salva-b** [comment]
i was thinking in call a function when finished selecting a date range. So, maybe when datetime dialog is closed

**Comment by mominsamir** [comment]
there are some emits on close event, i will check and let you know

**Comment by mominsamir** [comment]
$Scope Events for range picker
range-picker:startDateSelected
range-picker:startTimeSelected
range-picker:endDateSelected
range-picker:endTimeSelected
range-picker:close

$Scope Events for Date picker
calender:date-selected
calender:close

**Comment by mominsamir** [comment]
close issue if this is what u need.
