### ISSUE TITLE
Range Picker model value as object

### ISSUE THREAD

**Issue by mmaask** [mominsamir/smDateTimeRangePicker#27]
Why is the model value String, and not an object that contains 2 values respectivly, like startDate and endDate for example?

Any plan to change that, or am I forced to parse and split it all by myself?

**Comment by mominsamir** [comment]
I thought of this but I used it as string and my application parsed values on server side, I will add make that change range picker

**Comment by mominsamir** [comment]
I have added call back function onRangeSelect(range) 

Use as attribute to range picker directive on-range-select="vm.yourfunction(range)"

And in ur controller u will get range object via that call back function
