### ISSUE TITLE
Change Range Picker List

### ISSUE THREAD

**Issue by stevezau** [mominsamir/smDateTimeRangePicker#32]
Hey,

Is it possible to change the range picker list? I want to make it last 15 minutes, last hour, last 6 hours etc..

**Comment by mominsamir** [comment]
Check configuration option on home page of demo site

**Comment by stevezau** [comment]
thanks!

**Comment by mominsamir** [comment]
Just star repo if this is helpful

**Comment by stevezau** [comment]
done
