### ISSUE TITLE
Documentation on picker.setRangeDefaultList

### ISSUE THREAD

**Issue by stevezau** [mominsamir/smDateTimeRangePicker#33]
Hi,

On the readme and demo page it suggests we can change the default date range list via picker.setRangeDefaultList

Does this change it globally? I've tried to inject picker into a controller but there is no such method as setRangeDefaultList?

**Comment by mominsamir** [comment]
It's set that list globally via app config

**Comment by mominsamir** [comment]
solution I provided is that you required?

**Comment by stevezau** [comment]
sorry for the slow response. 

I tried via appConfig but from memory setRangeDefaultList didn't exist in the pickerProvider? Also the doc suggests to use picker in app.conf but how can that be if the provider is not available yet?

Another note: I only need 1 daterange picker but i suspect other may want to customise the ranges for different areas of their site. It might be a good enhancement to allow specifying of the range via the directive ?

**Comment by mominsamir** [comment]
I will make changes to allow configuration via directive attribute to change default list per instance

**Comment by mikajey** [comment]
Hi All.
Is it already added?
If yes. What is the attribute name?

**Comment by mominsamir** [comment]
Yes this is fixed check API here 

http://mominsamir.github.io/smDateTimeRangePicker/#/range-picker-api

**Comment by mominsamir** [comment]
Attribute name is custom-list

**Comment by mikajey** [comment]
Thanks.

**Comment by mikajey** [comment]
It only overrides items with same indexes.
How to override whole array?
I want to remove some items.
How to do that?

**Comment by mominsamir** [comment]
same way just pass whole array to custom list for that particular instance of range picker,
if you want to override globally then do it via pickerprovider.

**Comment by mikajey** [comment]
I tried, but I can't decries the size of array

**Comment by mominsamir** [comment]
Size of array is fixed to six that can not be reduced or increase as of now
