### ISSUE TITLE
how to disable month click 

### ISSUE THREAD

**Issue by osamabari** [mominsamir/smDateTimeRangePicker#34]

**Comment by mominsamir** [comment]
Can you provide me details where and what

**Comment by osamabari** [comment]
actually i want to remove on-click event from month name i dont want to give user control to change year

**Comment by mominsamir** [comment]
U want remove button year selection button, that's not possible as of now. But it's good use case I will implement it

**Comment by osamabari** [comment]
k thnaks

**Comment by mominsamir** [comment]
I will close the issue with commit

**Comment by osamabari** [comment]
k

**Comment by mominsamir** [comment]
disable-year-selection="true"
