### ISSUE TITLE
Choose time show blank content

### ISSUE THREAD

**Issue by yinxianwei** [mominsamir/smDateTimeRangePicker#37]
gif:

![gif](https://raw.githubusercontent.com/yinxianwei/files/master/images/smdatetime.gif)

**Comment by mominsamir** [comment]
I will check and fix it ASAP

**Comment by yinxianwei** [comment]
Thx!

**Comment by cpae** [comment]
Might be a problem with the "md-virtual-repeat". Quick (and dirty) solution was for me to replace them with the angular-"ng-repeat".

**Comment by mominsamir** [comment]
thank i will virtual-repeat with ng-repeat

**Comment by mominsamir** [comment]
Thank you for help
