### ISSUE TITLE
Customizing daterange picker

### ISSUE THREAD

**Issue by salva-b** [mominsamir/smDateTimeRangePicker#4]
Hi again Samir,
is it possible to make 'Start Date' and 'End Date' buttons to jump between them?
Thx!

**Comment by mominsamir** [comment]
Yes it is possible to jump between them, but I  have to changes.  I will test it and if it works without creating any problem i will commit it

**Comment by salva-b** [comment]
Great! 
is it also possible when cancelling custom range to return to main menu?
Thx in advance!
