### ISSUE TITLE
Angular 2 integration?

### ISSUE THREAD

**Issue by pratikthecook** [mominsamir/smDateTimeRangePicker#41]
Is this on your roadmap? because this is byfar the best date time picker with all the functionalities and UI/UX. 
Would love to see it, since there aren't any Material DateTime Picker, making one for angular2(Typescript) would be a hit.

**Comment by mominsamir** [comment]
Yes it is , but right now I am busy on some other project, however try start by next month

**Comment by mominsamir** [comment]
new repo is created and soon start commit for ES6 based component https://github.com/mominsamir/smDateTimeRangePicker2
