### ISSUE TITLE
Datepicker does not clean up properly

### ISSUE THREAD

**Issue by electronstorm** [mominsamir/smDateTimeRangePicker#44]
All the pickers leave one `<div id="picker>` per picker behind.  That means 3 pickers on a single page leave 3 divs behind. Everytime you change views (and change back) and open the pickers again, a new set of divs is created. This does eventually lead to a large number of redundant divs.

Code Sample:
Easy to replicate in the demo provided (http://mominsamir.github.io/smDateTimeRangePicker).  Just open the pickers, switch back and forth between the demos. The developer view of the browser will show a ton of divs.

Here is what I ended up with:
![image](https://cloud.githubusercontent.com/assets/7889636/16764894/406b2f82-4831-11e6-8175-28e03e7f9f72.png)

**Comment by mominsamir** [comment]
I will check and fix this issue
