### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by mirik123** [mominsamir/smDateTimeRangePicker#45]
Please add package to NPM repository.
Than the DIST folder should contains only the 2 output files picker.js/picker.css without the demo site sources.

Thanks in advance!

**Comment by mominsamir** [comment]
I will add it npm however instead of dist folder those two files are in src folder .

**Comment by mominsamir** [comment]
added to npm. check and confirm

**Comment by mirik123** [comment]
It works well, thanks.

It would be also nice to have a feature of setting time seconds.
It is quite easy to implement, one just need to clone all minutes relevant code parts.

**Comment by mominsamir** [comment]
Create issue for seconds selection, I will add in version 2.0.0
