### ISSUE TITLE
Min-date and Max-date not working on date range picker

### ISSUE THREAD

**Issue by kamal0808** [mominsamir/smDateTimeRangePicker#47]
Check this screenshot highlighted code from your Plunker code. Min-date not working for range picker.

![screenshot 2016-08-17 19 15 13](https://cloud.githubusercontent.com/assets/15616412/17738455/f70414f4-64ae-11e6-8bc3-8c46042c5eaf.png)

**Comment by lgoudriaan** [comment]
same for normal date picker
