### ISSUE TITLE
value isnt available in controller

### ISSUE THREAD

**Issue by claudioschneider** [mominsamir/smDateTimeRangePicker#51]
Hello

I'm just using this daterangepicker plugin and i really like it, but how can i get the value into my controller?
is this possible?

Cheers

**Comment by mominsamir** [comment]
you can use call back function see the documentation for same

**Comment by claudioschneider** [comment]
Where can i find it? (link)

**Comment by mominsamir** [comment]
http://mominsamir.github.io/smDateTimeRangePicker/#/date-time-picker-api

**Comment by claudioschneider** [comment]
i cant find anything about call back functions ..

**Comment by mominsamir** [comment]
date-select-call="vm.startDateSelected(date)"

**Comment by mominsamir** [comment]
try this for date, close this if it works

**Comment by claudioschneider** [comment]
so put date-select-call="vm.startDateSelected(date)" into my view
made call back function in my controller startDateSelected(date)..

doesnt work ..

**Comment by claudioschneider** [comment]
i found what i need in the demo (http://mominsamir.github.io/smDateTimeRangePicker/#/range-picker-demo) 
is there a demo like that on plunkr?

**Comment by mominsamir** [comment]
that is only for Range picker, I checked my repo and unfortunately i have not added call back for DatePicker.

I will add it and commit it back

**Comment by claudioschneider** [comment]
i need it for range picker

**Comment by claudioschneider** [comment]
the callback works now but it doesnt gives me a date object ..
just an empty string -.-

**Comment by mominsamir** [comment]
u want moment object, are u using date Picker or range Picker

**Comment by claudioschneider** [comment]
range Picker

**Comment by mominsamir** [comment]
range picker will give u selected date with format u provided, It wont give u moment object,

I am working on next version 2.0.0, i will add that in that version. 

will try to release that by end of this week.

**Comment by claudioschneider** [comment]
ok nice. 
but shouldn't there be any output in console if my callback func looks like:
`
this.startDateSelected = function(date) {
          console.log(date);
};`

**Comment by claudioschneider** [comment]
hey it works now ..
i just gave the attribute value="date" to my <sm-range-picker-input....></sm-range-picker-input> and used it in my filters ..
no call back func needed or something like that

So thank you for your help and your awesome daterangepicker :)

**Comment by mominsamir** [comment]
U can star it :)
