### ISSUE TITLE
Support for Angular 1.5.8

### ISSUE THREAD

**Issue by lshaf** [mominsamir/smDateTimeRangePicker#53]
Do this plugin not supported for angular 1.5.*?
I just try install this via composer and got this

```
bower-asset/smDateTimeRangePicker v1.6.1 requires bower-asset/angular ~1.4.5 -> no matching package found.
```

**Comment by mominsamir** [comment]
it should work, I will update bower package

**Comment by lshaf** [comment]
and 1 thing.
whenever I click button submit, why date range value become timestamp?

**Comment by lshaf** [comment]
big thanks :)

**Comment by lshaf** [comment]
@mominsamir bower still not updated. got this message
`- bower-asset/smDateTimeRangePicker v1.6.1 requires bower-asset/angular ~1.4.5 -> no matching package found.`

**Comment by mominsamir** [comment]
Reason it's not pulling up due to version , u need to pull head and not last version of picker 1.6.1

**Comment by mominsamir** [comment]
Last commit is not realese under any version

**Comment by lshaf** [comment]
I'm not understand, I'm not really detail about bower.
I put this onto my composer `"bower-asset/smDateTimeRangePicker": "*"`

**Comment by mominsamir** [comment]
Yes that should pull latest commit

**Comment by lshaf** [comment]
and the fact, it's still show that message

**Comment by lshaf** [comment]
btw have you update your bower to server?
I think you can't only update package.json to github only.
That's all I know :/

**Comment by mominsamir** [comment]
Ok I will release new version once I reach home that will help u fix the issue

**Comment by lshaf** [comment]
Great thanks mate 😄 
you help me a lot

**Comment by mominsamir** [comment]
ser "bower-asset/smDateTimeRangePicker": "dce26e4"

**Comment by lshaf** [comment]
it must be version of bower version mate.
You can't set it to push ID.
