### ISSUE TITLE
Two way data binding doesn't work 

### ISSUE THREAD

**Issue by Vitya11** [mominsamir/smDateTimeRangePicker#55]
Calendar reflect date on value property (value="model.someDate") on first load. But after changing this property on controller it doesn't reflect on calendar (the previous value remains as selected). 
Maybe there is some way to update this property at the same time as on controller?

**Comment by mominsamir** [comment]
value attribute is depreciated , you should use ng-model instead.

**Comment by Vitya11** [comment]
Yes, but on version 2.0 i can not use ng-model instead of value

**Comment by mominsamir** [comment]
http://plnkr.co/edit/2ePb5nf8vH71iH5byP7q?p=preview 

this uses ng-model and its version 2.0

**Comment by Vitya11** [comment]
When i use ng-model and try to change this value from controller i get this error : https://docs.angularjs.org/error/$compile/nonassign?p0=undefined&p1=value&p2=smDateTimePicker

I mean, it happens when I change value in controller without using picker

**Comment by mominsamir** [comment]
Ok I understood your problem, This is happening due to picker unable to update changed model from controller. try scope.$apply(). if this does not resolve issue i will look in to it

**Comment by Vitya11** [comment]
No, it does not work. Here is example: http://plnkr.co/edit/fh8XX0n7j6gcq9r0TQbA?p=preview
Maybe i make something wrong?

**Comment by mominsamir** [comment]
i will check and fix if any bug found

**Comment by huangjun604** [comment]
@mominsamir When using bower to install `smDateTimeRangePicker`, the version is not correct, in `.bower.json` is 2.0.0, but for `bower.json` is 1.6.0. And the code is still using `value` in `DateTimePicker` directive

**Comment by Vitya11** [comment]
I have the same behaviour

**Comment by mominsamir** [comment]
yes got that will fix soon in commit

**Comment by voidsteed** [comment]
same problem here, it shows me 1.6.0

**Comment by mominsamir** [comment]
@voidsteed i have fixed versioning issue pull version 2.0.1

**Comment by Vitya11** [comment]
Now when i download version 2.0.1 in bower.json it shows as 1.6.1

**Comment by mominsamir** [comment]
https://github.com/mominsamir/smDateTimeRangePicker/blob/master/bower.json

thats not possible check above link, I think u need to remove catch and re download

**Comment by Vitya11** [comment]
Yes, but in package.json i have 1.6.1. Or it`s ok?
https://github.com/mominsamir/smDateTimeRangePicker/blob/master/package.json

**Comment by mominsamir** [comment]
If u are using package json in that case u can submit pull request with updated package json and I will merge it. That will fix the version issue

**Comment by voidsteed** [comment]
Thanks, @mominsamir . I will try it and let you know.

**Comment by salesengineonline** [comment]
range picker has an issue with two way binding 

http://plnkr.co/edit/AsICpXjWWz8cie8WyLtZ?p=preview

**Comment by PhilippS93** [comment]
First of all, thank you for this great date picker!

I´m using your plugin as follows:

   `<sm-range-picker-input
             fname="date" 
             form="dateForm"
             format="{{model.filters.date.format}}" 
             ng-model="model.query.date" 
             custom-to-home="'true'" 
             show-custom="'true'"
             divider="To"
             flex="100"
             on-range-select="rangeSelected(range)">
    </sm-range-picker-input>`

But the model.query.date gets never updated. Whats wrong here?
