### ISSUE TITLE
can't find module fs

### ISSUE THREAD

**Issue by aviadhahami** [mominsamir/smDateTimeRangePicker#57]
Hey, im hitting the following error
![image](https://cloud.githubusercontent.com/assets/7353632/19156856/f1878326-8beb-11e6-837f-f4de796d433d.png)
I've just installed this freshly and required it via
`import 'smdatetimerangepicker` globaly.

Nevertheless, when I used the module like this:
`import 'smdatetimerangepicker/src/picker'`
`import 'smdatetimerangepicker/src/picker.css'`
I made it work properly. Any clue?

**Comment by mominsamir** [comment]
are you using type script and angular 2?

**Comment by aviadhahami** [comment]
@mominsamir nope, angular 1.5 (es6+) with webpack

**Comment by mominsamir** [comment]
This module does not support es6

**Comment by aviadhahami** [comment]
It doesn't have to support it as I'm transpiling the code via babel....
