### ISSUE TITLE
How to avoid .action to impact other code?

### ISSUE THREAD

**Issue by huangjun604** [mominsamir/smDateTimeRangePicker#59]
There is a piece of code in CSS:

```
.action {
  height: 30px;
  margin-bottom: 0;
  position: absolute;
  bottom: 0;
  width: 100%; }

```

Because it is in the root, so it will work on the whole project, which means all the class `action` in my project will be impacted by this CSS.

**Comment by mominsamir** [comment]
I will update css in picker and commit code
