### ISSUE TITLE
ReferenceError: o is not defined

### ISSUE THREAD

**Issue by aodavid** [mominsamir/smDateTimeRangePicker#61]
I use smDateTimeRangePicker like your plunker shows, but i met some issues:
1.  vm.value undefined undefined show 16 times
2. when select date,  ReferenceError: o is not defined; i change the ng-model to my model like info.date;
3. document said:
`pickerProvider.setDayHeader('single'); //Options 'single','shortName', 'fullName' 
     picker.setDaysNames([`
what's the picker? is it pickerProvider? is there a spelling error?
4. I can't custom monthName, even i change picker to pickerProvider, but it  works for custom DayName

Please give me some advice, thanks a lot.

**Comment by mominsamir** [comment]
Any service injected in App config is injected as provider. so Its Picker Services but injected to config it becomes provider 

In your config you have to inject as pickerProvider

**Comment by mominsamir** [comment]
app.config(function ($stateProvider, $urlRouterProvider,$mdThemingProvider,pickerProvider) {

```
pickerProvider.setDayHeader('single');

pickerProvider.setOkLabel('Save');
```

}

**Comment by aodavid** [comment]
Thx for your reply, I injected pickerProvider service in config. and use pickerProvider to setDaysNames and setMonthNames, setDaysNames works, but setMonthNames not work;

Besides, how about my question 1 and 2?

**Comment by mominsamir** [comment]
I am in process of fixing that issue,

Somehow I messed up everything while working on version 2.0.  

I am reviewing and will fix all bugs reported
