### ISSUE TITLE
ES6 Compatibility

### ISSUE THREAD

**Issue by Ganbin** [mominsamir/smDateTimeRangePicker#64]
Hello,

First I want to tell you that I find your date and time picker really nice and well designed.

I think this plugin can have a great success if it open to an ES6 module syntax so other framework can use and integrate it easily.

I like the range and time picker which are not easy to find with material design. Well job.

So did you plan to open this plugin to an ES6 module syntax?

For the feedback. I can tell you that in the demo web page, the range input have a bug on the "Last Month" When we click, it select the start of the last month but not the end. It keep the day of today.

And also as a improvement, I think when we choose "Custom Range" and then select the start date, we should be able to change the start date before to choose the end date if we have made a mistake. We should be able to reset the start date by clicking on the start date tab.

That's my feedback.

Great Job. Continue on this way.

**Comment by mominsamir** [comment]
new repo is created and soon start commit for ES6 based component https://github.com/mominsamir/smDateTimeRangePicker2
