### ISSUE TITLE
 Broken @import declaration of "https://fonts.googleapis.com/icon?family=Material+Icons" - timeout

### ISSUE THREAD

**Issue by jhpassion0621** [mominsamir/smDateTimeRangePicker#65]
Hi. I am using your library on my project. It's very perfect. Thanks for your sharing this good library. It works on gulp serve but when I build gulp, I am getting broken import issue. How can I fix it?

**Comment by mominsamir** [comment]
can you check now?

**Comment by oleg-demkovych** [comment]
Fixed:
cleanCss({processImport: false}) in gulp file
