### ISSUE TITLE
I'm getting a deprecation warning

### ISSUE THREAD

**Issue by michelem09** [mominsamir/smDateTimeRangePicker#66]
> Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
> Error

```
<sm-range-picker-input
	fname="dayOfPay" 
	lable="Date of Pay"
	form="empForm"
	ng-model="vm.dateOfPay"
	format="MM-DD-YYYY"
	min-date="01-01-2012"
	mode="date" 
	week-start-day="Monday">
</sm-range-picker-input>
```

Where `vm.dateOfPay = new Date()`

**Comment by mominsamir** [comment]
you should try vm.dateOfPay = moment(); this module does not support casting date to moment object.
