### ISSUE TITLE
ng-model doesn't update after a resource callback (.get())

### ISSUE THREAD

**Issue by pilucdes** [mominsamir/smDateTimeRangePicker#68]
The ng-model doesn't update after a scope has been changed in a resource callback (ex: .get() )

     Quotation.get({ Id: $routeParams.id }, function (result) {
                    $scope.vmdate = result.date;
                });

**Comment by mominsamir** [comment]
can you try now?

**Comment by pilucdes** [comment]
The date now appear but is not formatted

```
Controller :   `$scope.quotation.CreatedDateDisplay = moment($scope.quotation.CreatedDate).format("lll");`
```

HTML : `  
<sm-date-time-picker flex="50"

```
                         on-focus
                         flex-xs="100"
                         fname="field"
                         disable-year-selection="true"
                         label="Creation date"
                         ng-model="quotation.CreatedDateDisplay"
                         is-required="{{true}}"
                         format="lll"
                         mode="date-time"
                         week-start-day="Monday"
                         on-date-selected-call="dtpCreatedDateSelected(date)">
    </sm-date-time-picker>`
```

I also try this -> $scope.quotation.CreatedDateDisplay = new Date(); but still not formatted as lll

**Comment by mominsamir** [comment]
in call back date will not be formatted as it is moment object, you have to format in controller
