### ISSUE TITLE
Datepicker separate model from value

### ISSUE THREAD

**Issue by salva-b** [mominsamir/smDateTimeRangePicker#7]
Hi,
is it possible to separate the model from shown value in datepicker input (like an angular filter works). Maybe having an ng-model and values attribute.
Now, if I change date format with format attribute ng-model changes to the new format so that changes my source data model.

**Comment by mominsamir** [comment]
http://mominsamir.github.io/date-time-picker/#/date-time-picker-demo ,
I have created a service to pick a date using angular material dailog component. see at bottom a button service in date picker demo page.

to use it follow my example at here https://github.com/mominsamir/date-time-picker/blob/master/app/scripts/controllers/main.js

https://github.com/mominsamir/date-time-picker/blob/master/app/views/date-time-picker-demo.html

I hope this helps you.

**Comment by salva-b** [comment]
Nice! I see when selecting two times a date with service you can't select anymore on chrome. Are options configurable as a provider?

Me i was thinking in something like in bootstrap datepicker do, like:

`<input ng-model="dataRecord.date" data-date-format="dd-MM-yyyy" bs-datepicker value="{{dataRecord.date | date: dd/MM/yyyy}}">`

This way you can mantain data source model and you don't need extra code in controller.
This might work on your project? 
Thx!

**Comment by mominsamir** [comment]
I have added call back function however not documented it, check out on src code

**Comment by mominsamir** [comment]
I will try to fix this in version 2.0
