### ISSUE TITLE
Time icon in the date view

### ISSUE THREAD

**Issue by praveenk-telsiz** [mominsamir/smDateTimeRangePicker#75]
I am trying to add the 'time' icon as shown in the demo in the link 'http://mominsamir.github.io/date-time-picker/#/date-time-picker-demo' (in date of pay example). 

For some reasons, I cannot achieve it and it always takes me to the time selection once the dat is selected. I could not find the documentations as well. 

It would be really helpful if you can post a snippet or point me to a example to achieve this.

![screen shot 2016-11-16 at 1 37 33 pm](https://cloud.githubusercontent.com/assets/17713687/20366874/e37250c8-ac01-11e6-9248-6773ca7c08f4.png)

**Comment by mominsamir** [comment]
Time icon is depreciated, Please check the demo here http://mominsamir.github.io/smDateTimeRangePicker/

**Comment by praveenk-telsiz** [comment]
Thanks !
