### ISSUE TITLE
Editing the input field do not update the calender.

### ISSUE THREAD

**Issue by praveenk-telsiz** [mominsamir/smDateTimeRangePicker#76]
Is there a way an edit in the input field results in the calendar to update itself as well?

**Comment by mominsamir** [comment]
yes this is work in progress

**Comment by praveenk-telsiz** [comment]
Great ! Any idea on the estimate release?

**Comment by mominsamir** [comment]
i am not promising but i am working, also have hell lot of work from Office :(

**Comment by praveenk-telsiz** [comment]
I understand. This is great work you have already put up. Thanks !

**Comment by S0c5** [comment]
Up!

**Comment by praveenk-telsiz** [comment]
@mominsamir Ar you planning to release this as a . version?

**Comment by mominsamir** [comment]
version 2.0.5

**Comment by praveenk-telsiz** [comment]
@mominsamir  This needs to be reopened. The problem is the calender gets the updated value but the ng-model do not get updated.

**Comment by mominsamir** [comment]
Please submit ur pr and i will meagre it

**Comment by praveenk-telsiz** [comment]
I don't know how can I submit a PR. But here is the solution:

On picker.js,

while construction the template, add a ng-change to input tag, say data-ng-change="vm.onDateEdited(vm.value)"

Here is how the template construction looks like:

 if(attributes.hasOwnProperty('onFocus')){
            inputType =  '<input name="{{vm.fname}}" ng-model="vm.value" '
                  + '  type="text" placeholder="{{vm.label}}" data-ng-change="vm.onDateEdited(vm.value)"'
                  + '  aria-label="{{vm.fname}}" ng-focus="vm.show()" data-ng-required="vm.isRequired"  ng-disabled="vm.disable"'
                  + '  server-error class="sm-input-container" />'
              + '     <md-button tabindex="-1" class="sm-picker-icon md-icon-button" aria-label="showCalender" ng-disabled="vm.disable" aria-hidden="true" type="button" ng-click="vm.show()">'
              + '     <md-icon class="material-icons md-light">today</md-icon></md-button>' ;

          }else{
             inputType = '      <input class="" name="{{vm.fname}}" ng-model="vm.value" '
                      + '             type="text" placeholder="{{vm.label}}" data-ng-change="vm.onDateEdited(vm.value)"'
                      + '             aria-label="{{vm.fname}}" aria-hidden="true" data-ng-required="vm.isRequired"  ng-disabled="vm.disable"/>'
                      + '     <md-button tabindex="-1" class="sm-picker-icon md-icon-button" aria-label="showCalender" ng-disabled="vm.disable" aria-hidden="true" type="button" ng-click="vm.show()">'
                      + '         <svg  fill="#000000" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M7 10l5 5 5-5z"/><path d="M0 0h24v24H0z" fill="none"/></svg>'
                      + '     <i class="material-icons md-light">today</i></md-button>' ;
          }

And write a change handler at its controller.

SMDateTimePickerCtrl.prototype.onDateEdited = function (date) {
  var self = this;
  if (moment(date, self.format).format(self.format) !== "Invalid date") {
    self.currentDate = date;
    self.ngModelCtrl.$setViewValue(date);
    self.ngModelCtrl.$render();
    self.value = date;
  }
}
