### ISSUE TITLE
When the icon is cliked and a date and time is selected, the calendar closes but the bubble animation on the icon still remains.  

### ISSUE THREAD

**Issue by praveenk-telsiz** [mominsamir/smDateTimeRangePicker#77]
![screen shot 2016-11-16 at 5 32 12 pm](https://cloud.githubusercontent.com/assets/17713687/20373201/7d9678dc-ac25-11e6-87d9-a8e75b6f9bfd.png)

**Comment by mominsamir** [comment]
this caused due to re focusing button after date is selected

**Comment by praveenk-telsiz** [comment]
Do we have any work around for this?

**Comment by mominsamir** [comment]
there is no fix, its kept that way only

**Comment by praveenk-telsiz** [comment]
Thanks !
