### ISSUE TITLE
Feature to select am/ pm inside time picker Dialog

### ISSUE THREAD

**Issue by GeorgeChackungal** [mominsamir/smDateTimeRangePicker#79]
Hi There,

Can you please add the feature to select am/pm in 12hr time picker?

**Comment by mominsamir** [comment]
Picker allows u to select time and than convert it to your require format just pass it as attribute format="your format".

**Comment by devlemire** [comment]
What format would convert it to 12 hr?

**Comment by mominsamir** [comment]
format it using moment http://momentjs.com/docs/#/displaying/
for 12 hour time use  "dd-MMM-yyyy HH:mm A"

**Comment by devlemire** [comment]
I selected 16 and got "06-December-2016 16:25 PM" using this format "DD-MMMM-YYYY HH:mm A"

Is there a way to make it turn into 4:25 PM?

**Comment by mominsamir** [comment]
try DD-MMMM-YYYY hh:mm A

**Comment by devlemire** [comment]
Sweet, thanks.

**Comment by devlemire** [comment]
Do you have time to check my open issue?  https://github.com/mominsamir/smDateTimeRangePicker/issues/85

**Comment by mominsamir** [comment]
i am fixing issued one by one, sure i will check.
