### ISSUE TITLE
Resolve problem from the library, when moment not is defined

### ISSUE THREAD

**Issue by Hcata** [mominsamir/smDateTimeRangePicker#81]

**Comment by pablorsk** [comment]
#80 :)

**Comment by mominsamir** [comment]
hay this is resolved if yes please close the issue

**Comment by pablorsk** [comment]
The problem was solved, but I think we put code on generated final JS file.

This is the removed code, https://github.com/mominsamir/smDateTimeRangePicker/commit/cd9fd3f89b5f04a47b5bb0f797a4f5b19ebbf189#diff-d3386db72668eb7dd21d95bd4d49c4d4L1

Where is the correct place @mominsamir?
