### ISSUE TITLE
Mode time

### ISSUE THREAD

**Issue by PabloPG** [mominsamir/smDateTimeRangePicker#90]
When I create an input "mode='time'", the hours do not appear. Another case, when I choose an hour, they disappear

http://plnkr.co/edit/UV9qM9YISukWBlKYPSuF?p=preview

**Comment by mominsamir** [comment]
to pick time you should use time picker, I missed to add the documentation, I will update documentation soon.

**Comment by mominsamir** [comment]
Use                 <sm-time-picker-new 
                    fname="Date of Pay" 
                    lable="Date of Pay"
                    form="empForm"
                    value="vm.employee.timeselect24" 
                    flex-size="50"
                    mode="time"                         
                    is-required="true" 
                    format="HH:mm">
                </sm-time-picker-new>

**Comment by mominsamir** [comment]
<sm-time-picker-new 
                    fname="Date of Pay" 
                    lable="Date of Pay"
                    form="empForm"
                    value="vm.employee.timeselect24" 
                    flex-size="50"
                    mode="time"                         
                    is-required="true" 
                    format="HH:mm">
                </sm-time-picker-new>
